module.exports.CHANNEL_CONFIG_REQUEST = 'CHAINCODE_CONFIG_REQUEST';
module.exports.CHAINCODE_PACKAGE_REQUEST = 'CHAINCODE_PACKAGE_REQUEST';
module.exports.CHANNEL_CONFIG_RESPONSE = 'CHANNEL_CONFIG_RESPONSE'